# action.yml
name: 'Builder for Swift projects that support WebAssembly'
description: 'This action has SwiftWasm toolchain, SDK and developer tools preinstalled for your CI needs'
inputs:
  shell-action:
    description: 'Shell action to run'
    required: false
    default: 'carton test'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/swiftwasm/swiftwasm-action:5.8'
  args:
    - ${{ inputs.shell-action }}
